### ISSUE TITLE
Missing Delete -functions

### ISSUE THREAD

**Issue by aoinas** [xBimTeam/XbimDocs#2]
IModel -interface has Delete -function and XbimModel's Delete  -implementation uses IfcPersistentInstanceCache.Delete_Reversable, which throws NotImplementedException.

Is it possible to remove instances from ifc file ( or xbim file ) using XbimModel or any other way?

**Comment by martin1cerny** [comment]
Current implementation in 'master' branch doesn't support delete. There is a new implementation of IModel in 'develop' branch which lives entirely in memory and it supports `Delete(IPersistEntity entity)` function. However, be careful as it is very expensive operations because it needs to go through the entire model to find all objects referencing the object to keep the model consistent. It is not a problem for a single deletion or for a small models and it depends how many objects can actually reference this type of object (we don't browse every single entity if it doesn't have any property of this type). But it is not trivial.

**Comment by aoinas** [comment]
Oh, great to hear. I will try it out. Thanks!
